-- OptiDesk initial D1 schema.
--
-- IDs are generated by the Worker as UUIDv4 text values. Timestamps use
-- SQLite's UTC clock and ISO-8601 text so they sort lexicographically and can
-- be exchanged with the Web API without timezone ambiguity. Financial values
-- are integer paise; application code must recalculate and validate totals
-- before writing a purchase or payment.
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS application_metadata (
  id TEXT PRIMARY KEY NOT NULL,
  metadata_key TEXT NOT NULL,
  metadata_value TEXT NOT NULL,
  description TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CHECK (length(id) > 0),
  CHECK (length(metadata_key) BETWEEN 1 AND 128)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_application_metadata_key
  ON application_metadata (metadata_key);

CREATE TABLE IF NOT EXISTS admin_users (
  id TEXT PRIMARY KEY NOT NULL,
  email TEXT NOT NULL COLLATE NOCASE,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'owner'
    CHECK (role IN ('owner', 'staff')),
  password_hash TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'disabled')),
  last_login_at TEXT,
  failed_login_count INTEGER NOT NULL DEFAULT 0
    CHECK (failed_login_count >= 0),
  locked_until TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at TEXT,
  created_by_admin_id TEXT,
  deleted_by_admin_id TEXT,
  CHECK (length(id) > 0),
  CHECK (length(trim(email)) > 3),
  CHECK (length(trim(display_name)) > 0),
  CHECK (deleted_at IS NULL OR status = 'disabled'),
  FOREIGN KEY (created_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (deleted_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_admin_users_active_email
  ON admin_users (email)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_admin_users_status
  ON admin_users (status, deleted_at);

CREATE TABLE IF NOT EXISTS settings (
  id TEXT PRIMARY KEY NOT NULL,
  setting_key TEXT NOT NULL,
  setting_value TEXT NOT NULL,
  value_type TEXT NOT NULL DEFAULT 'string'
    CHECK (value_type IN ('string', 'integer', 'boolean', 'json')),
  is_secret INTEGER NOT NULL DEFAULT 0
    CHECK (is_secret IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at TEXT,
  created_by_admin_id TEXT,
  updated_by_admin_id TEXT,
  deleted_by_admin_id TEXT,
  CHECK (length(id) > 0),
  CHECK (length(setting_key) BETWEEN 1 AND 128),
  CHECK (deleted_at IS NULL OR deleted_by_admin_id IS NOT NULL),
  FOREIGN KEY (created_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (deleted_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_settings_active_key
  ON settings (setting_key)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_settings_deleted
  ON settings (deleted_at, setting_key);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY NOT NULL,
  admin_user_id TEXT NOT NULL,
  token_hash TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  last_seen_at TEXT,
  revoked_at TEXT,
  ip_address TEXT,
  user_agent TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CHECK (length(id) > 0),
  CHECK (length(token_hash) > 0),
  CHECK (revoked_at IS NULL OR revoked_at <= expires_at),
  FOREIGN KEY (admin_user_id) REFERENCES admin_users (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_sessions_token_hash
  ON sessions (token_hash);

CREATE INDEX IF NOT EXISTS idx_sessions_admin_user
  ON sessions (admin_user_id, revoked_at, expires_at);

CREATE INDEX IF NOT EXISTS idx_sessions_expiry
  ON sessions (expires_at, revoked_at);

CREATE TABLE IF NOT EXISTS login_attempts (
  id TEXT PRIMARY KEY NOT NULL,
  identifier TEXT NOT NULL COLLATE NOCASE,
  ip_address TEXT,
  admin_user_id TEXT,
  was_successful INTEGER NOT NULL DEFAULT 0
    CHECK (was_successful IN (0, 1)),
  failure_reason TEXT,
  attempted_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  request_id TEXT,
  CHECK (length(id) > 0),
  CHECK (was_successful = 1 OR failure_reason IS NOT NULL),
  FOREIGN KEY (admin_user_id) REFERENCES admin_users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_login_attempts_identifier_time
  ON login_attempts (identifier, attempted_at DESC);

CREATE INDEX IF NOT EXISTS idx_login_attempts_ip_time
  ON login_attempts (ip_address, attempted_at DESC);

CREATE INDEX IF NOT EXISTS idx_login_attempts_admin_user_time
  ON login_attempts (admin_user_id, attempted_at DESC);

CREATE TABLE IF NOT EXISTS customers (
  id TEXT PRIMARY KEY NOT NULL,
  customer_number TEXT,
  full_name TEXT NOT NULL,
  phone TEXT,
  email TEXT COLLATE NOCASE,
  date_of_birth TEXT,
  address_line_1 TEXT,
  address_line_2 TEXT,
  city TEXT,
  state TEXT,
  postal_code TEXT,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at TEXT,
  created_by_admin_id TEXT,
  updated_by_admin_id TEXT,
  deleted_by_admin_id TEXT,
  deletion_reason TEXT,
  CHECK (length(id) > 0),
  CHECK (length(trim(full_name)) > 0),
  CHECK (deleted_at IS NULL OR deleted_by_admin_id IS NOT NULL),
  FOREIGN KEY (created_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (deleted_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_customers_active_number
  ON customers (customer_number)
  WHERE customer_number IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_customers_name
  ON customers (full_name COLLATE NOCASE, deleted_at);

CREATE INDEX IF NOT EXISTS idx_customers_phone
  ON customers (phone, deleted_at);

CREATE INDEX IF NOT EXISTS idx_customers_email
  ON customers (email, deleted_at);

CREATE TABLE IF NOT EXISTS prescriptions (
  id TEXT PRIMARY KEY NOT NULL,
  customer_id TEXT NOT NULL,
  prescription_type TEXT NOT NULL DEFAULT 'spectacle'
    CHECK (prescription_type IN ('spectacle', 'contact_lens', 'other')),
  prescribed_on TEXT,
  expires_on TEXT,
  prescriber_name TEXT,
  right_sphere TEXT,
  right_cylinder TEXT,
  right_axis INTEGER,
  right_addition TEXT,
  left_sphere TEXT,
  left_cylinder TEXT,
  left_axis INTEGER,
  left_addition TEXT,
  pupillary_distance TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'archived')),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at TEXT,
  created_by_admin_id TEXT,
  updated_by_admin_id TEXT,
  deleted_by_admin_id TEXT,
  CHECK (length(id) > 0),
  CHECK (right_axis IS NULL OR (right_axis BETWEEN 0 AND 180)),
  CHECK (left_axis IS NULL OR (left_axis BETWEEN 0 AND 180)),
  CHECK (expires_on IS NULL OR prescribed_on IS NULL OR expires_on >= prescribed_on),
  CHECK (deleted_at IS NULL OR deleted_by_admin_id IS NOT NULL),
  FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (deleted_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_prescriptions_customer_date
  ON prescriptions (customer_id, prescribed_on DESC, deleted_at);

CREATE INDEX IF NOT EXISTS idx_prescriptions_active
  ON prescriptions (customer_id, status, deleted_at);

CREATE TABLE IF NOT EXISTS tax_profiles (
  id TEXT PRIMARY KEY NOT NULL,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  rate_basis_points INTEGER NOT NULL
    CHECK (rate_basis_points >= 0 AND rate_basis_points <= 10000),
  is_active INTEGER NOT NULL DEFAULT 1
    CHECK (is_active IN (0, 1)),
  effective_from TEXT,
  effective_to TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at TEXT,
  created_by_admin_id TEXT,
  updated_by_admin_id TEXT,
  deleted_by_admin_id TEXT,
  CHECK (length(id) > 0),
  CHECK (length(trim(code)) > 0),
  CHECK (length(trim(name)) > 0),
  CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
  CHECK (deleted_at IS NULL OR deleted_by_admin_id IS NOT NULL),
  FOREIGN KEY (created_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (deleted_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tax_profiles_active_code
  ON tax_profiles (code)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_tax_profiles_active_dates
  ON tax_profiles (is_active, effective_from, effective_to, deleted_at);

CREATE TABLE IF NOT EXISTS purchases (
  id TEXT PRIMARY KEY NOT NULL,
  invoice_number TEXT,
  customer_id TEXT,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'issued', 'partially_paid', 'paid', 'void', 'refunded')),
  currency_code TEXT NOT NULL DEFAULT 'INR'
    CHECK (length(currency_code) = 3),
  subtotal_paise INTEGER NOT NULL DEFAULT 0
    CHECK (subtotal_paise >= 0),
  discount_paise INTEGER NOT NULL DEFAULT 0
    CHECK (discount_paise >= 0 AND discount_paise <= subtotal_paise),
  tax_paise INTEGER NOT NULL DEFAULT 0
    CHECK (tax_paise >= 0),
  total_paise INTEGER NOT NULL DEFAULT 0
    CHECK (total_paise = subtotal_paise - discount_paise + tax_paise),
  notes TEXT,
  issued_at TEXT,
  completed_at TEXT,
  voided_at TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at TEXT,
  created_by_admin_id TEXT,
  updated_by_admin_id TEXT,
  deleted_by_admin_id TEXT,
  deletion_reason TEXT,
  CHECK (length(id) > 0),
  CHECK (deleted_at IS NULL OR deleted_by_admin_id IS NOT NULL),
  CHECK (status = 'draft' OR invoice_number IS NOT NULL),
  CHECK (status IN ('draft', 'void') OR issued_at IS NOT NULL),
  FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (deleted_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_purchases_active_invoice_number
  ON purchases (invoice_number)
  WHERE invoice_number IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_purchases_customer_date
  ON purchases (customer_id, created_at DESC, deleted_at);

CREATE INDEX IF NOT EXISTS idx_purchases_status_date
  ON purchases (status, created_at DESC, deleted_at);

CREATE INDEX IF NOT EXISTS idx_purchases_issued_at
  ON purchases (issued_at DESC, deleted_at);

CREATE TABLE IF NOT EXISTS purchase_items (
  id TEXT PRIMARY KEY NOT NULL,
  purchase_id TEXT NOT NULL,
  prescription_id TEXT,
  tax_profile_id TEXT,
  line_type TEXT NOT NULL DEFAULT 'product'
    CHECK (line_type IN ('product', 'service', 'adjustment')),
  description TEXT NOT NULL,
  sku TEXT,
  quantity INTEGER NOT NULL DEFAULT 1
    CHECK (quantity > 0),
  unit_price_paise INTEGER NOT NULL
    CHECK (unit_price_paise >= 0),
  discount_paise INTEGER NOT NULL DEFAULT 0
    CHECK (discount_paise >= 0 AND discount_paise <= quantity * unit_price_paise),
  tax_paise INTEGER NOT NULL DEFAULT 0
    CHECK (tax_paise >= 0),
  line_total_paise INTEGER NOT NULL
    CHECK (line_total_paise = quantity * unit_price_paise - discount_paise + tax_paise),
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at TEXT,
  created_by_admin_id TEXT,
  updated_by_admin_id TEXT,
  deleted_by_admin_id TEXT,
  deletion_reason TEXT,
  CHECK (length(id) > 0),
  CHECK (length(trim(description)) > 0),
  CHECK (deleted_at IS NULL OR deleted_by_admin_id IS NOT NULL),
  FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON DELETE RESTRICT,
  FOREIGN KEY (prescription_id) REFERENCES prescriptions (id) ON DELETE SET NULL,
  FOREIGN KEY (tax_profile_id) REFERENCES tax_profiles (id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (deleted_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_purchase_items_purchase_order
  ON purchase_items (purchase_id, sort_order, deleted_at);

CREATE INDEX IF NOT EXISTS idx_purchase_items_prescription
  ON purchase_items (prescription_id, deleted_at);

CREATE TABLE IF NOT EXISTS payments (
  id TEXT PRIMARY KEY NOT NULL,
  purchase_id TEXT NOT NULL,
  amount_paise INTEGER NOT NULL CHECK (amount_paise > 0),
  payment_method TEXT NOT NULL
    CHECK (payment_method IN ('cash', 'card', 'upi', 'bank_transfer', 'other')),
  status TEXT NOT NULL DEFAULT 'settled'
    CHECK (status IN ('pending', 'settled', 'voided', 'refunded')),
  reference TEXT,
  received_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  settled_at TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at TEXT,
  created_by_admin_id TEXT,
  updated_by_admin_id TEXT,
  deleted_by_admin_id TEXT,
  deletion_reason TEXT,
  CHECK (length(id) > 0),
  CHECK (status IN ('pending', 'settled') OR settled_at IS NOT NULL),
  CHECK (deleted_at IS NULL OR deleted_by_admin_id IS NOT NULL),
  FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (deleted_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_payments_purchase_date
  ON payments (purchase_id, received_at DESC, deleted_at);

CREATE INDEX IF NOT EXISTS idx_payments_status_date
  ON payments (status, received_at DESC, deleted_at);

CREATE TABLE IF NOT EXISTS payment_reversals (
  id TEXT PRIMARY KEY NOT NULL,
  payment_id TEXT NOT NULL,
  amount_paise INTEGER NOT NULL CHECK (amount_paise > 0),
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'posted'
    CHECK (status IN ('posted', 'voided')),
  reversed_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  created_by_admin_id TEXT,
  voided_at TEXT,
  voided_by_admin_id TEXT,
  CHECK (length(id) > 0),
  CHECK (length(trim(reason)) > 0),
  CHECK (status = 'posted' OR voided_at IS NOT NULL),
  FOREIGN KEY (payment_id) REFERENCES payments (id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL,
  FOREIGN KEY (voided_by_admin_id) REFERENCES admin_users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_payment_reversals_payment_date
  ON payment_reversals (payment_id, reversed_at DESC, status);

CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY NOT NULL,
  actor_admin_user_id TEXT,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  before_json TEXT,
  after_json TEXT,
  metadata_json TEXT,
  request_id TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CHECK (length(id) > 0),
  CHECK (length(trim(action)) > 0),
  CHECK (length(trim(entity_type)) > 0),
  CHECK (length(trim(entity_id)) > 0),
  FOREIGN KEY (actor_admin_user_id) REFERENCES admin_users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_time
  ON audit_logs (entity_type, entity_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_time
  ON audit_logs (actor_admin_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_request
  ON audit_logs (request_id, created_at DESC);

-- Audit records are append-only. Corrections should be represented by a new
-- event, never by mutating the original record.
CREATE TRIGGER IF NOT EXISTS audit_logs_immutable_update
BEFORE UPDATE ON audit_logs
BEGIN
  SELECT RAISE(ABORT, 'audit_logs are immutable');
END;

CREATE TRIGGER IF NOT EXISTS audit_logs_immutable_delete
BEFORE DELETE ON audit_logs
BEGIN
  SELECT RAISE(ABORT, 'audit_logs are immutable');
END;
