import { expect, test, type Page } from '@playwright/test'
import type { PurchaseDetail, PurchaseList } from '../shared/purchases'
import { mutationHeaders, signIn } from './session'

async function customer(page: Page, name: string, phone: string) {
  const response = await page.request.post('/api/customers', { headers: await mutationHeaders(page), data: { name, phone } })
  expect(response.status()).toBe(201)
  return (await response.json()).data as { uuid: string }
}
async function noOverflowOrStorage(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(await page.evaluate(() => localStorage.length + sessionStorage.length)).toBe(0)
}
function item(page: Page, index: number) { return page.getByRole('group', { name: `Item ${index}`, exact: true }) }
for (const viewport of [{ label: 'Desktop', width: 1440, height: 960, suffix: '1' }, { label: 'Mobile', width: 390, height: 844, suffix: '2' }]) {
  test(`${viewport.label}: customer profile, multiple items, exact totals, specific prescription selection, duplicate protection and immutable purchase details`, async ({ page }) => {
    await page.setViewportSize(viewport)
    const failures: string[] = []
    page.on('pageerror', error => failures.push(error.message))
    await signIn(page)
    const profile = await customer(page, `${viewport.label} Purchase profile`, `952456700${viewport.suffix}`)
    const api = `/api/customers/${profile.uuid}/purchases`
    const headers = await mutationHeaders(page)
    const prescriptionResponse = await page.request.post(`/api/customers/${profile.uuid}/prescriptions`, { headers, data: { prescribed_on: '2026-04-01', right_sphere: '-1.25' } })
    expect(prescriptionResponse.status()).toBe(201)
    const prescription = (await prescriptionResponse.json()).data as { uuid: string }
    await page.goto(`/customers/${profile.uuid}`)
    await expect(page.getByRole('heading', { name: `${viewport.label} Purchase profile`, exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'No purchases yet', exact: true })).toBeVisible()
    await page.getByRole('link', { name: 'Add purchase', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Add purchase', exact: true })).toBeVisible()
    await page.getByLabel('Purchase date', { exact: true }).fill('2026-04-08')
    await expect(page.getByLabel('Link prescription (optional)', { exact: true }).locator('option', { hasText: 'Version 1' })).toHaveCount(1)
    await page.getByLabel('Link prescription (optional)', { exact: true }).selectOption(prescription.uuid)
    await item(page, 1).getByLabel('Product name / description', { exact: true }).fill('Original frame')
    await item(page, 1).getByLabel('Quantity', { exact: true }).fill('2')
    await item(page, 1).getByLabel('Unit price (₹)', { exact: true }).fill('125.50')
    await item(page, 1).getByLabel('Line discount (₹)', { exact: true }).fill('0.50')
    await page.getByRole('button', { name: 'Add item', exact: true }).click()
    await item(page, 2).getByLabel('Product name / description', { exact: true }).fill('Original lenses')
    await item(page, 2).getByLabel('Product category', { exact: true }).selectOption('prescription_lenses')
    await item(page, 2).getByLabel('Quantity', { exact: true }).fill('3')
    await item(page, 2).getByLabel('Unit price (₹)', { exact: true }).fill('0.10')
    await item(page, 2).getByLabel('Line discount (₹)', { exact: true }).fill('0.01')
    await page.getByLabel('Purchase discount (₹)', { exact: true }).fill('1.00')
    await page.getByLabel('Purchase notes', { exact: true }).fill('Recorded fitting note\nSecond line')
    await expect(page.getByTestId('line-preview-0')).toHaveText('₹250.50')
    await expect(page.getByTestId('line-preview-1')).toHaveText('₹0.29')
    await expect(page.getByTestId('purchase-total-preview')).toHaveText('₹249.79')
    await noOverflowOrStorage(page)
    await page.screenshot({ path: `test-results/phase-four-${viewport.label.toLowerCase()}-form.png`, fullPage: true })
    let writes = 0
    page.on('request', request => { if (new URL(request.url()).pathname === api && request.method() === 'POST') writes++ })
    const response = page.waitForResponse(response => new URL(response.url()).pathname === api && response.request().method() === 'POST')
    // Two simultaneous DOM submits exercise the actual synchronous UI lock.
    await page.getByRole('form', { name: 'New purchase', exact: true }).evaluate(form => { form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })); form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })) })
    const received = await response
    expect(received.status()).toBe(201)
    const purchase = (await received.json()).data as PurchaseDetail
    expect(purchase).toMatchObject({ prescription_uuid: prescription.uuid, subtotal_paise: 25130, discount_paise: 151, total_paise: 24979 })
    expect(purchase.items).toHaveLength(2)
    await expect(page).toHaveURL(new RegExp(`/customers/${profile.uuid}/purchases/${purchase.uuid}$`, 'u'))
    await expect(page.getByRole('heading', { name: 'Purchase details', exact: true })).toBeVisible()
    await expect(page.getByRole('status').filter({ hasText: 'Purchase saved.' })).toContainText('Purchase saved.')
    await expect(page.getByTestId('purchase-grand-total')).toHaveText('₹249.79')
    await expect(page.getByRole('list', { name: 'Purchase items', exact: true }).getByRole('listitem')).toHaveCount(2)
    await expect(page.getByRole('link', { name: /View linked prescription/u })).toHaveAttribute('href', `/customers/${profile.uuid}/prescriptions/${prescription.uuid}`)
    await page.reload()
    await expect(page.getByTestId('purchase-grand-total')).toHaveText('₹249.79')
    await expect(page.getByText('Recorded fitting note\nSecond line', { exact: true })).toBeVisible()
    expect(writes).toBe(1)
    const revision = await page.request.patch(`/api/customers/${profile.uuid}/prescriptions/${prescription.uuid}`, { headers, data: { prescribed_on: '2026-05-01', right_sphere: '-2.25', revision_reason: 'New source' } })
    expect(revision.status()).toBe(201)
    await page.reload()
    await expect(page.getByRole('link', { name: /View linked prescription/u })).toHaveAttribute('href', `/customers/${profile.uuid}/prescriptions/${prescription.uuid}`)
    await noOverflowOrStorage(page)
    await page.screenshot({ path: `test-results/phase-four-${viewport.label.toLowerCase()}-details.png`, fullPage: true })
    await page.getByRole('link', { name: 'Back to customer', exact: true }).click()
    const history = page.getByRole('list', { name: 'Purchase history', exact: true })
    await expect(history.getByRole('listitem')).toHaveCount(1)
    await expect(history.getByRole('listitem')).toContainText('₹249.79')
    await history.getByRole('link', { name: /View purchase details/u }).click()
    await expect(page.getByTestId('purchase-grand-total')).toHaveText('₹249.79')
    expect(failures).toEqual([])
  })

  test(`${viewport.label}: empty items, strict validation, add/remove, unsaved navigation/back/reload guards, optional prescription and archive safety`, async ({ page }) => {
    await page.setViewportSize(viewport)
    await signIn(page)
    const profile = await customer(page, `${viewport.label} Purchase guards`, `962456700${viewport.suffix}`)
    const api = `/api/customers/${profile.uuid}/purchases`
    let writes = 0
    page.on('request', request => { if (new URL(request.url()).pathname === api && request.method() === 'POST') writes++ })
    await page.goto(`/customers/${profile.uuid}`)
    await page.getByRole('link', { name: 'Add purchase', exact: true }).click()
    await expect(page.getByText('No prescriptions recorded. You can save this purchase without one.', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Remove item 1', exact: true }).click()
    await page.getByRole('button', { name: 'Save purchase', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('Add at least one purchase item.')
    expect(writes).toBe(0)
    await page.getByRole('button', { name: 'Add item', exact: true }).click()
    await item(page, 1).getByLabel('Product name / description', { exact: true }).fill('Unsaved accessory')
    await item(page, 1).getByLabel('Quantity', { exact: true }).fill('1.5')
    await item(page, 1).getByLabel('Unit price (₹)', { exact: true }).fill('0.001')
    await page.getByRole('button', { name: 'Save purchase', exact: true }).click()
    await expect(item(page, 1).getByLabel('Quantity', { exact: true })).toHaveAttribute('aria-invalid', 'true')
    await expect(item(page, 1).getByLabel('Unit price (₹)', { exact: true })).toHaveAttribute('aria-invalid', 'true')
    await expect(page.getByTestId('purchase-total-preview')).toHaveText('—')
    expect(writes).toBe(0)
    const dialog = page.getByRole('dialog', { name: 'Discard unsaved changes?', exact: true })
    for (const action of ['cancel', 'internal', 'back']) {
      if (action === 'cancel') await page.getByRole('button', { name: 'Cancel', exact: true }).click()
      if (action === 'internal') await page.getByRole('link', { name: 'Back to customer', exact: true }).click()
      if (action === 'back') await page.goBack()
      await expect(dialog).toBeVisible()
      await expect(dialog.getByRole('button', { name: 'Keep editing', exact: true })).toBeFocused()
      await dialog.getByRole('button', { name: 'Keep editing', exact: true }).click()
      await expect(item(page, 1).getByLabel('Product name / description', { exact: true })).toHaveValue('Unsaved accessory')
    }
    const prompt = page.waitForEvent('dialog')
    await page.evaluate(() => { setTimeout(() => window.location.reload(), 0) })
    const unload = await prompt
    expect(unload.type()).toBe('beforeunload')
    await unload.dismiss()
    await item(page, 1).getByLabel('Quantity', { exact: true }).fill('1')
    await item(page, 1).getByLabel('Unit price (₹)', { exact: true }).fill('10.00')
    await item(page, 1).getByLabel('Line discount (₹)', { exact: true }).fill('10.01')
    await page.getByRole('button', { name: 'Save purchase', exact: true }).click()
    await expect(item(page, 1).getByLabel('Line discount (₹)', { exact: true })).toHaveAttribute('aria-invalid', 'true')
    await item(page, 1).getByLabel('Line discount (₹)', { exact: true }).fill('0')
    await page.getByRole('button', { name: 'Add item', exact: true }).click()
    await page.getByRole('button', { name: 'Remove item 2', exact: true }).click()
    const response = page.waitForResponse(response => new URL(response.url()).pathname === api && response.request().method() === 'POST')
    await page.getByRole('button', { name: 'Save purchase', exact: true }).click()
    expect((await response).status()).toBe(201)
    await expect(page.getByText('No prescription linked', { exact: true })).toBeVisible()
    await expect(page.getByTestId('purchase-grand-total')).toHaveText('₹10.00')
    const purchaseUuid = new URL(page.url()).pathname.split('/').at(-1)!
    await page.getByRole('link', { name: 'Back to customer', exact: true }).click()
    await page.getByRole('button', { name: 'Archive customer', exact: true }).click()
    await page.getByRole('dialog', { name: 'Archive customer?', exact: true }).getByRole('button', { name: 'Archive customer', exact: true }).click()
    await expect(page.getByRole('link', { name: 'Add purchase', exact: true })).toHaveCount(0)
    await expect(page.getByRole('list', { name: 'Purchase history', exact: true }).getByRole('listitem')).toHaveCount(1)
    await page.goto(`/customers/${profile.uuid}/purchases/new`)
    await expect(page.getByRole('heading', { name: 'Purchase cannot be added', exact: true })).toBeVisible()
    await page.goto(`/customers/${profile.uuid}/purchases/${purchaseUuid}`)
    await expect(page.getByTestId('purchase-grand-total')).toHaveText('₹10.00')
    await noOverflowOrStorage(page)
    expect(writes).toBe(1)
  })

  test(`${viewport.label}: real purchase pagination beyond twenty and date/category filters`, async ({ page }) => {
    await page.setViewportSize(viewport)
    await signIn(page)
    const profile = await customer(page, `${viewport.label} Paged purchases`, `972456700${viewport.suffix}`)
    const headers = await mutationHeaders(page)
    const api = `/api/customers/${profile.uuid}/purchases`
    for (let day = 1; day <= 22; day++) {
      const result = await page.request.post(api, { headers, data: { client_request_id: crypto.randomUUID(), purchase_date: `2026-04-${String(day).padStart(2, '0')}`, items: [{ description: `Item ${day}`, product_category: day % 2 ? 'sunglasses' : 'reading_glasses', quantity: 1, unit_price: '10.00' }] } })
      expect(result.status()).toBe(201)
    }
    const allResponse = await page.request.get(`${api}?pageSize=50`)
    const all = (await allResponse.json()).data as PurchaseList
    await page.goto(`/customers/${profile.uuid}`)
    const history = page.getByRole('list', { name: 'Purchase history', exact: true })
    const pagination = page.getByRole('navigation', { name: 'Purchase history pagination', exact: true })
    await expect(history.getByRole('listitem')).toHaveCount(20)
    await pagination.getByRole('button', { name: 'Next', exact: true }).click()
    await expect(history.getByRole('listitem')).toHaveCount(2)
    await expect(pagination.getByRole('status')).toHaveText('21–22 of 22 purchases · Page 2 of 2')
    expect(await history.getByRole('link').evaluateAll(elements => elements.map(element => element.getAttribute('href')))).toEqual(all.purchases.slice(20).map(row => `/customers/${profile.uuid}/purchases/${row.uuid}`))
    await pagination.getByLabel('Per page').selectOption('50')
    await expect(history.getByRole('listitem')).toHaveCount(22)
    await page.getByLabel('Purchases from', { exact: true }).fill('2026-04-02')
    await page.getByLabel('Purchases to', { exact: true }).fill('2026-04-04')
    await expect(history.getByRole('listitem')).toHaveCount(3)
    await page.getByLabel('Purchase category', { exact: true }).selectOption('reading_glasses')
    await expect(history.getByRole('listitem')).toHaveCount(2)
    await page.getByLabel('Purchase category', { exact: true }).selectOption('contact_lenses')
    await expect(page.getByRole('heading', { name: 'No matching purchases', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Clear purchase filters', exact: true }).click()
    await expect(history.getByRole('listitem')).toHaveCount(22)
    await noOverflowOrStorage(page)
    await page.screenshot({ path: `test-results/phase-four-${viewport.label.toLowerCase()}-history.png`, fullPage: true })
  })

  test(`${viewport.label}: paged prescription choices retain the selected version, server errors retain inputs, and a lost response cannot duplicate a saved purchase`, async ({ page }) => {
    await page.setViewportSize(viewport)
    await signIn(page)
    const profile = await customer(page, `${viewport.label} Purchase retry`, `982456700${viewport.suffix}`)
    const headers = await mutationHeaders(page)
    const api = `/api/customers/${profile.uuid}/purchases`
    let oldest = ''
    for (let day = 1; day <= 21; day++) {
      const result = await page.request.post(`/api/customers/${profile.uuid}/prescriptions`, { headers, data: { prescribed_on: `2026-04-${String(day).padStart(2, '0')}` } })
      expect(result.status()).toBe(201)
      if (day === 1) oldest = (await result.json()).data.uuid
    }
    await page.goto(`/customers/${profile.uuid}/purchases/new`)
    await page.getByRole('button', { name: 'Next prescriptions', exact: true }).click()
    const choice = page.getByLabel('Link prescription (optional)', { exact: true })
    await expect(choice.locator(`option[value="${oldest}"]`)).toHaveCount(1)
    await choice.selectOption(oldest)
    await page.getByRole('button', { name: 'Previous prescriptions', exact: true }).click()
    await expect(choice).toHaveValue(oldest)
    await item(page, 1).getByLabel('Product name / description', { exact: true }).fill('Preserved retry item')
    await item(page, 1).getByLabel('Unit price (₹)', { exact: true }).fill('10.01')
    await page.getByLabel('Purchase notes', { exact: true }).fill('Retained retry note')
    const archive = await page.request.delete(`/api/customers/${profile.uuid}`, { headers })
    expect(archive.status()).toBe(200)
    const rejected = page.waitForResponse(response => new URL(response.url()).pathname === api && response.request().method() === 'POST')
    await page.getByRole('button', { name: 'Save purchase', exact: true }).click()
    expect((await rejected).status()).toBe(409)
    await expect(page.getByRole('alert')).toContainText('Restore the customer before adding a purchase.')
    await expect(item(page, 1).getByLabel('Product name / description', { exact: true })).toHaveValue('Preserved retry item')
    await expect(page.getByLabel('Purchase notes', { exact: true })).toHaveValue('Retained retry note')
    expect((await page.request.post(`/api/customers/${profile.uuid}/restore`, { headers })).status()).toBe(200)
    // The backend really commits; discard only its response to simulate a lost
    // connection. The retry must use the same in-memory submission UUID.
    await page.route(`**${api}`, async route => {
      if (route.request().method() !== 'POST') { await route.continue(); return }
      const committed = await route.fetch()
      expect(committed.status()).toBe(201)
      await route.abort('failed')
      await page.unroute(`**${api}`)
    })
    await page.getByRole('button', { name: 'Save purchase', exact: true }).click()
    await expect(page.getByRole('alert')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Save purchase', exact: true })).toBeEnabled()
    const duplicateResponse = page.waitForResponse(response => new URL(response.url()).pathname === api && response.request().method() === 'POST')
    await page.getByRole('button', { name: 'Save purchase', exact: true }).click()
    const duplicate = await duplicateResponse
    expect(duplicate.status()).toBe(409)
    expect((await duplicate.json()).error.code).toBe('PURCHASE_DUPLICATE')
    await expect(page.getByRole('button', { name: 'Save purchase', exact: true })).toBeDisabled()
    await page.getByRole('link', { name: 'View purchase history', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    const history = page.getByRole('list', { name: 'Purchase history', exact: true })
    await expect(history.getByRole('listitem')).toHaveCount(1)
    await history.getByRole('link', { name: /View purchase details/u }).click()
    await expect(page.getByTestId('purchase-grand-total')).toHaveText('₹10.01')
    await expect(page.getByRole('link', { name: /View linked prescription/u })).toHaveAttribute('href', `/customers/${profile.uuid}/prescriptions/${oldest}`)
    await noOverflowOrStorage(page)
  })
}
