import { useQuery } from '@tanstack/react-query'
import { Link, useLocation, useParams } from 'react-router-dom'
import { PageHeader } from '../components/ui/PageHeader'
import { ErrorState, LoadingState } from '../components/ui/States'
import { ApiError } from '../lib/api'
import { customerDate, customerErrorMessage, customerKeys, customersApi } from '../lib/customers'
import { prescriptionDate } from '../lib/prescriptions'
import { categoryLabel, purchaseErrorMessage, purchaseKeys, purchaseMoney, purchasesApi } from '../lib/purchases'
import { PaymentHistory } from '../components/PaymentHistory'
import { PaymentStatusBadge, PurchasePaymentSummary } from '../components/PaymentSummary'
import { ActionLink } from '../components/ui/ShopUI'

export function PurchaseDetailPage() {
  const { uuid = '', purchaseUuid = '' } = useParams()
  const location = useLocation()
  const customer = useQuery({ queryKey: customerKeys.detail(uuid), queryFn: ({ signal }) => customersApi.detail(uuid, signal), retry: false })
  const purchase = useQuery({ queryKey: purchaseKeys.detail(uuid, purchaseUuid), queryFn: ({ signal }) => purchasesApi.detail(uuid, purchaseUuid, signal), enabled: customer.isSuccess, retry: false })
  const back = <Link to={`/customers/${uuid}?tab=sales`} className="text-sm font-medium text-ink underline underline-offset-4">Back to customer</Link>
  if (customer.isPending || (customer.isSuccess && purchase.isPending)) return <LoadingState label="Loading sale details…" />
  if (customer.isError) return <div className="space-y-5"><Link to="/customers" className="text-sm text-ink underline">Back to customers</Link><ErrorState title="Customer could not be loaded" description={customerErrorMessage(customer.error)} onRetry={() => void customer.refetch()} /></div>
  if (purchase.isError) return <div className="space-y-5">{back}<ErrorState title={purchase.error instanceof ApiError && purchase.error.status === 404 ? 'Sale not found' : 'Sale could not be loaded'} description={purchaseErrorMessage(purchase.error)} onRetry={() => void purchase.refetch()} /></div>
  if (!purchase.data) return <LoadingState label="Loading sale details…" />
  const record = purchase.data
  const notice = typeof location.state?.paymentNotice === 'string' ? location.state.paymentNotice : typeof location.state?.purchaseNotice === 'string' ? location.state.purchaseNotice : ''
  const payable = !customer.data.archived_at && record.outstanding_paise > 0 && !['void', 'refunded'].includes(record.status) && record.currency_code === 'INR'
  return <div className="space-y-8 [overflow-wrap:anywhere]">{back}<PageHeader eyebrow={`Sale · ${customer.data.name}`} title="Sale details" description={prescriptionDate(record.purchase_date)} actions={<><ActionLink secondary to={`/customers/${uuid}/purchases/${record.uuid}/invoice`}>View invoice</ActionLink>{payable ? <ActionLink to={`/receive-payment?customer=${uuid}&sale=${record.uuid}`}>Receive Payment</ActionLink> : null}</>} />
    {notice ? <p className="border-y border-line py-3 text-sm" role="status">{notice}</p> : null}
    <section aria-labelledby="sale-overview" className="space-y-3"><h2 id="sale-overview" className="text-[19px] font-semibold">Sale overview</h2><dl className="border-y border-line py-4 text-sm"><div className="flex items-center justify-between gap-4 py-2"><dt className="text-muted">Customer</dt><dd className="font-medium text-right">{customer.data.name}</dd></div><div className="flex items-center justify-between gap-4 py-2"><dt className="text-muted">Sale date</dt><dd className="text-right"><time dateTime={record.purchase_date}>{prescriptionDate(record.purchase_date)}</time></dd></div><div className="flex items-center justify-between gap-4 py-2"><dt className="text-muted">Prescription</dt><dd className="text-right">{record.prescription_uuid ? <Link to={`/customers/${uuid}/prescriptions/${record.prescription_uuid}`} className="text-accent underline-offset-4 hover:underline">View prescription</Link> : 'None'}</dd></div><div className="flex items-center justify-between gap-4 py-2"><dt className="text-muted">Recorded</dt><dd className="text-right">{customerDate(record.created_at, true)}</dd></div></dl></section>
    <section aria-labelledby="sale-items" className="space-y-3"><h2 id="sale-items" className="text-[19px] font-semibold">Items</h2><ul className="hairline-list border-y border-line bg-white" aria-label="Purchase items">{record.items.map((item, index) => <li key={item.uuid} className="space-y-3 px-4 py-5 sm:px-5"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold">{index + 1}. {item.description}</h3><p className="mt-1 text-sm text-muted">{categoryLabel(item.product_category)}</p></div><p className="font-semibold tabular-nums">{purchaseMoney(item.line_total_paise)}</p></div><dl className="grid grid-cols-2 gap-4 text-sm sm:grid-cols-4"><div><dt className="text-muted">Quantity</dt><dd className="mt-1 font-medium tabular-nums">{item.quantity}</dd></div><div><dt className="text-muted">Unit price</dt><dd className="mt-1 font-medium tabular-nums">{purchaseMoney(item.unit_price_paise)}</dd></div><div><dt className="text-muted">Discount</dt><dd className="mt-1 font-medium tabular-nums">{purchaseMoney(item.discount_paise)}</dd></div><div><dt className="text-muted">Line total</dt><dd className="mt-1 font-medium tabular-nums">{purchaseMoney(item.line_total_paise)}</dd></div></dl></li>)}</ul></section>
    <section aria-labelledby="sale-total" className="space-y-3"><h2 id="sale-total" className="text-[19px] font-semibold">Total</h2><dl className="space-y-3 border-y border-line py-4 text-sm tabular-nums"><div className="flex justify-between gap-4"><dt className="text-muted">Subtotal</dt><dd>{purchaseMoney(record.subtotal_paise)}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted">Discount</dt><dd>{purchaseMoney(record.discount_paise)}</dd></div>{record.tax_paise ? <div className="flex justify-between gap-4"><dt className="text-muted">Recorded tax</dt><dd>{purchaseMoney(record.tax_paise)}</dd></div> : null}<div className="flex justify-between gap-4 border-t border-line pt-4 text-base font-semibold"><dt>Grand total</dt><dd data-testid="purchase-grand-total">{purchaseMoney(record.total_paise)}</dd></div></dl></section>
    <section aria-labelledby="sale-payment" className="space-y-4"><div className="flex items-center justify-between gap-3"><h2 id="sale-payment" className="text-[19px] font-semibold">Payment</h2><PaymentStatusBadge status={record.payment_status} /></div><div className="border-y border-line py-5"><PurchasePaymentSummary summary={record} /></div>{payable ? <ActionLink to={`/customers/${uuid}/purchases/${record.uuid}/payments/new`}>Record Payment</ActionLink> : <p className="text-sm text-muted">{record.outstanding_paise === 0 ? 'This sale is fully paid.' : customer.data.archived_at ? 'Restore the customer before recording a payment.' : 'This historical sale cannot receive payments.'}</p>}</section>
    <PaymentHistory key={`payments:${record.uuid}`} customerUuid={uuid} purchaseUuid={record.uuid} />
    {record.notes ? <section aria-labelledby="sale-notes" className="space-y-3"><h2 id="sale-notes" className="text-[19px] font-semibold">Notes</h2><p className="whitespace-pre-wrap border-y border-line py-4 text-sm leading-6 text-muted">{record.notes}</p></section> : null}
  </div>
}
